export const MOCK_SAVED_LOCATIONS = [
  {
    latitude: 40.712776,
    longitude: -74.005974,
    name: 'Home',
    address: '123 Main St, New York, NY',
    type: 'home',
  },
  {
    latitude: 40.758896,
    longitude: -73.985130,
    name: 'Work',
    address: '350 Fifth Avenue, New York, NY',
    type: 'work',
  },
];

export const MOCK_RIDES = [
  {
    id: 'ride1',
    date: 'Today',
    time: '10:30 AM',
    status: 'completed',
    pickup: '123 Main St, New York, NY',
    destination: 'Times Square, New York, NY',
    price: 24.56,
    driverName: 'John Smith',
    driverRating: 4.8,
    driverPhoto: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'ride2',
    date: 'Yesterday',
    time: '5:45 PM',
    status: 'canceled',
    pickup: 'Central Park, New York, NY',
    destination: 'Brooklyn Bridge, New York, NY',
    price: 18.75,
  },
  {
    id: 'ride3',
    date: 'Jul 25, 2023',
    time: '9:15 AM',
    status: 'completed',
    pickup: '350 Fifth Avenue, New York, NY',
    destination: 'Grand Central Station, New York, NY',
    price: 15.29,
    driverName: 'Sarah Johnson',
    driverRating: 4.9,
    driverPhoto: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
  {
    id: 'ride4',
    date: 'Jul 22, 2023',
    time: '2:00 PM',
    status: 'completed',
    pickup: 'Statue of Liberty, New York, NY',
    destination: 'One World Trade Center, New York, NY',
    price: 32.45,
    driverName: 'Michael Brown',
    driverRating: 4.6,
    driverPhoto: 'https://images.pexels.com/photos/3785079/pexels-photo-3785079.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
  },
];